In [1]:
list(filter(lambda x:x%2==0,[1, 2, 3, 4, 5]))

[2, 4]

In [119]:
## FULL PYRAMID PATTERN WITH NUMBERS

rows = int(input("Enter Triangle Numbers Pattern Rows = "))
print("====The Triangle Numbers Pattern====")
for i in range(1, rows + 1): # Controls the rows
    for j in range(rows, i, -1): # controls the spaces
        print(end = ' ')
    for k in range(1, i+1): # K controls the columns
        print(i, end = ' ')
    print()

Enter Triangle Numbers Pattern Rows = 8
====The Triangle Numbers Pattern====
       1 
      2 2 
     3 3 3 
    4 4 4 4 
   5 5 5 5 5 
  6 6 6 6 6 6 
 7 7 7 7 7 7 7 
8 8 8 8 8 8 8 8 


In [127]:
for i in range(1,6):
    for j in range(1,i+1):
        print(i, end=" ")
        
    print(" ")

1  
2 2  
3 3 3  
4 4 4 4  
5 5 5 5 5  


In [ ]:
# Print inverted half pyramid as shown below

1 1 1 1 1

2 2 2 2

3 3 3

4 4 

5


In [140]:
rows = 5
c=0
for i in range (rows,0,-1):
    c = c+1
    for j in range(1,i+1):
        print(c,end=" ")
    print('\n')

1 1 1 1 1 

2 2 2 2 

3 3 3 

4 4 

5 



In [126]:
for j in range(4,1,-1):
    print(j)

4
3
2


In [132]:
for i in range(5,1,-1):
    print(i)

5
4
3
2


In [142]:
num=int(input("Enter the number = "))
rev=0
n=num
while(n !=0):
   r = n % 10
   rev = rev * 10 + r
   n=n//10
if(num == rev):
   print(num, " is Palindrome")
else:
   print(num, "is not a Palindrome")

Enter the number = 123454321
123454321  is Palindrome


In [146]:
num = input("Enter number: ")
if num == num[::-1]:
    print("it is a palindrome")
else:
    print("not a palindrome")

Enter number: 123454321
it is a palindrome


In [4]:
n = int(input())
arr = list(map(int,input().split()))
print(sorted(list(set(arr)))[-2])

6
1 2 3 4 5 6
5


In [14]:
list(arr)

[1, 2, 3, 5, 5, 6, 6]

In [16]:
x = set(arr)

In [17]:
x

{1, 2, 3, 5, 6}

In [18]:
sorted(list(x))[-2]

5

In [15]:
y = sorted(list(arr))[-2]
print(y)

6


In [20]:
a = (1,2,5,4,6,3)
b = sorted(a)
print(b)

[1, 2, 3, 4, 5, 6]


In [22]:
a = (1,2,5,4,6,3)
b = sorted(a, reverse = True)
print(b)
print(type(b))

[6, 5, 4, 3, 2, 1]
<class 'list'>


inversion Count for an array indicates – how far (or close) the array is from being sorted. If the array is already sorted, then the inversion count is 0, but if the array is sorted in the reverse order, the inversion count is the maximum. 
Formally speaking, two elements a[i] and a[j] form an inversion if a[i] > a[j] and i < j 
Example: 

Input: arr[] = {8, 4, 2, 1}
Output: 6
Explanation: Given array has six inversions:
(8, 4), (4, 2), (8, 2), (8, 1), (4, 1), (2, 1).

Input: arr[] = {3, 1, 2}
Output: 2
Explanation: Given array has two inversions:
(3, 1), (3, 2) 

In [6]:
# Write a function to count Inversions in an array


# input arr[] = {8,4,2,1}
# output = 6

# input arr[] = {3,1,2}
# output = 2

def inv_count(arr,n):
    count = 0
    for i in range(n):
        for j in range(i+1,n):
            if(arr[i]>arr[j]):
                count = count+1
    return count
            

In [7]:
arr = [3,1,2]
n = len(arr)
print("Inversion count is : ", inv_count(arr,n))

Inversion count is :  2


# Python Class and Object 

Python is an object oriented programming language.

Almost everything in Python is an object, with its properties and methods.

A Class is like an object constructor, or a "blueprint" for creating objects.

Object is anything in the real world that has some unique characteristics.It has state and behavior. eg: Mouse, keyboard, chair, table, etc

Class is a collection of objects. It is a logical entity that has some specific attributes and methods. eg: If you have a student class, then it should contain an attribute and method viz name, standard, age, etc

Inheritance means one object acquires properties and behavior of the parent object.

The new class is known as the Derived class or Child class.

And from which inherited the properties is called as Base class or Parent class.

Inheritance provides reusability of the code.

Method Overiding

Polymorphism: one object many forms.

Data Abstraction/Data Hiding

Data Encapsulation/ Data Binding

In [29]:
a = [1,2,3,4,5]
print(type(a))

<class 'list'>


In [27]:
class college:
    Name = ''
    Marks = 0
    Gender = ''

In [28]:
s1 = college()
print(type(s1))

<class '__main__.college'>


In [30]:
s1 = college()
s1.Name = "Mike"
s1.Marks = 90
s1.Gender = "M"



In [31]:
print(s1.Name,s1.Marks,s1.Gender)

Mike 90 M


In [34]:
s2 = college()
s2.Name = "Adrain"
s2.Marks = 46
s2.Gender = "M"

In [35]:
print(s2.Name,s2.Marks,s2.Gender)

Adrain 46 M


# Self Attribute

> the first attribute of every class method is always a referece to the current instance of the class

> by convetion, this argument is names as self

> self is not a reserved keyword.

> remember that writing self as the first attribute as a syntax

In [8]:
class xyz:
    def abc(self,n):
        print("Hello i am class", n)

In [9]:
s = xyz()

In [10]:
s.abc("college dunia")

Hello i am class college dunia


In [39]:
def abc(n):
    print("Hello i am class", n)

In [40]:
abc("college dunia")

Hello i am class college dunia


In [12]:
class xyz:
    def abc(self,n):
        n = n+1
        print(n)
        

In [13]:
s = xyz()#object creation
s.abc(100)

101


# Inheritance :

> Inhereitance will have a base class and a derived class

> Animal is base class and Dog is derived class

1. Single Inheritance

2. Multiple Inheritance

3. Multilevel Inheritance

In [6]:
# single inheritance

class father:
    def s1(self):
        print("I am base class")
        
class son(father):
    def s2(self):
        print("I am derived class")

In [7]:
o = son()
o.s1()
o.s2()

I am base class
I am derived class


In [9]:
class animal:
    def afunc(self):
        print("i m in animal class")
        
class cat(animal):
    def cfunc(self):
        print(" im in cat class")

In [12]:
a=animal()
c=cat()
a.afunc()
c.afunc()
c.cfunc()
a.cfunc()


i m in animal class
i m in animal class
 im in cat class


AttributeError: 'animal' object has no attribute 'cfunc'

In [25]:
f = father()
f.s1()
f.s2()

I am base class


AttributeError: 'father' object has no attribute 's2'

In [26]:
# Multiple Inheritance

class st1: # father
    def num1(self):
        self.n1 = 7
        print("num1",self.n1)
        
class st2: # mother
    def num2(self):
        self.n2 = 10
        print("num2:", self.n2)
        
class st(st1,st2): # son/daughter
    def add(self):
        return self.n1+self.n2

In [27]:
s = st()
s.num1()
s.num2()
s.add()

num1 7
num2: 10


17

In [28]:
y = st1()
y.add()

AttributeError: 'st1' object has no attribute 'add'

# Method overriding

> Method overriding is an ability of any object - oriented programming language that allows a subclass or child class to provide a specfic implementation of a method that is already provided by one of it super class or parent class

In [56]:
class T:
    def show(self):
        print("base class method called")
        
class S(T):
    def sme(self):
        print("Derived class method called")
        
        

In [57]:
class T:
    def show(self):
        print("base class method called")
        
class S(T):
    def show(self):
        print("Derived class method called")
        
        
V = S()
V.show()

Derived class method called


In [39]:
class Bottle:
    def show(self,clor):
        print("base class method called")
        
class Material(Bottle):
    def materials(self, mat_1,clor):
        print("The material of the bottle is ", mat_1, "and the color is ", clor)
   

In [42]:
M=Material()
M.show("Pink")
M.materials("Plastic","pink")

base class method called
The material of the bottle is  Plastic and the color is  pink


In [33]:
import numpy as np
a=np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,4,0,1],[1,0,0,0,1],[1,1,1,1,1]])
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 4 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
